version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: "build(repo)"
    ignore:
      - dependency-name: typescript
        update-types: [version-update:semver-major]

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup
    schedule: { interval: monthly }
    commit-message:
      prefix: "ci(repo)"

  - package-ecosystem: docker
    directory: /ops/deploy
    schedule: { interval: monthly }
    commit-message:
      prefix: "build(ops)"
