/**
 * Primer 스토리 그림마다 **그 그림에 보이는 것**을 적는다.
 *
 * 전부 `.output/references/probe.json`에 남은 관찰(원소의 실제 글자·자식 구조·크기)을 보고 썼고,
 * 글자가 없어 관찰만으로 모자란 것(아이콘·아바타·진행 막대 따위)은 그림을 열어 확인했다.
 * **"우리 어느 컴포넌트 자리다" 같은 판단은 안 적는다** — 그것은 사람이 한다(→ ADR 0008·0010).
 */
export const PRIMER_NOTES = {
  "action-bar":
    "오른쪽에 붙는 아이콘만의 도구 줄. 굵게·기울임·코드·링크 뒤에 세로 구분선을 두고 추가·찾기·목록 넷이 이어진다",
  "action-list":
    "글자만 있는 항목 세 줄(Copy link · Quote reply · Edit comment)이 세로로 쌓인 목록. 항목 사이 구분선이 없고 좌우 여백이 같다",
  "action-menu": "누르면 목록이 열리는 버튼 하나(Open menu). 닫힌 상태라 방아쇠만 보인다",
  "anchored-overlay": "떠 있는 판을 붙일 기준 버튼(Button) 하나. 닫힌 상태다",
  announce: "화면 낭독기에 알릴 글 한 줄(Default message). 보이는 모양은 평범한 글줄이다",
  "aria-alert": "긴급 알림으로 읽히는 글 한 줄(Default message). 시각적으로는 글줄과 같다",
  "aria-status": "상태 변화를 알리는 글 한 줄(Default message). 시각적으로는 글줄과 같다",
  autocomplete: "라벨이 붙은 입력칸과 그 위에 누른 키를 보여주는 줄(Last key pressed: none). 후보 목록은 닫혀 있다",
  avatar: "동그랗게 잘린 아바타 한 장. 24px 남짓이다",
  "avatar-stack": "동그란 아바타 셋이 서로 겹쳐 왼쪽부터 포개진 줄. 앞의 것이 뒤의 것을 테두리로 덮는다",
  banner: "아이콘·제목·본문·버튼 둘이 한 칸에 담긴 알림 띠. 'Info'로 톤을 밝히고 본문은 여러 줄로 감긴다",
  blankslate:
    "비어 있음을 알리는 큰 판 — 제목(Welcome to the mona wiki!), 여러 줄 설명, 아래에 행동 버튼. 세로 여백이 크다",
  "branch-name": "브랜치 이름을 고정폭 글꼴과 알약 배경으로 감싼 짧은 표식(branch_name)",
  breadcrumbs: "구분자로 이어지는 경로 링크 줄(Home › About › Team). 마지막 칸이 현재 자리다",
  button: "기본 버튼 하나(Default). 높이 32px, 테두리와 옅은 배경을 가진다",
  "button-group": "버튼 셋이 틈 없이 붙어 한 덩어리가 된 줄. 바깥 모서리만 둥글다",
  card: "제목·설명·보조 정보(3 contributors)를 담은 상자. 테두리로 구역을 만들고 안쪽 여백이 넓다",
  checkbox: "네모 체크 상자와 라벨 한 쌍(Default label)",
  "checkbox-group": "제목(Choices) 아래 체크 상자 셋이 세로로 선다. 하나에는 필수 표시(*)가 붙는다",
  "confirmation-dialog": "확인을 묻는 대화상자를 여는 버튼(Show dialog). 닫힌 상태다",
  "counter-label": "숫자를 감싼 작은 알약(12). 옆 글에 붙어 개수를 나타낸다",
  "css-component": "CSS만으로 만든 버튼 하나(Default). React 컴포넌트와 같은 모양을 클래스로 낸다",
  "data-table": "제목·부제 아래 열 다섯짜리 표 — 저장소 이름·종류·갱신 시각·상태 둘. 머리 줄과 본문 줄의 높이가 다르다",
  details: "펼침 삼각형과 요약 줄(See Details). 접힌 상태다",
  dialog: "대화상자를 여는 버튼(Show dialog). 닫힌 상태다",
  "filtered-action-list":
    "제목·설명·검색칸 아래 라벨 목록이 이어진다. 치는 대로 걸러진다는 안내가 검색칸 자리에 적혀 있다",
  "form-control": "라벨(필수 표시 포함)·입력칸·아래 설명 한 줄이 한 덩어리로 묶인 폼 한 칸",
  header: "제품 머리 줄 — 왼쪽 로고(GitHub)와 메뉴. 어두운 배경에 높이 64px다",
  heading: "제목 글 한 줄(Default H2 Heading). 본문보다 크고 굵다",
  hidden: "화면 폭에 따라 감추고 드러내는 것을 설명하는 글줄. 보이는 모양은 평범한 문단이다",
  "icon-button": "아이콘 하나만 든 정사각 버튼(하트). 32×32에 글자가 없다",
  "inline-message": "글줄 사이에 끼는 짧은 안내 한 줄(An example inline message)",
  "issue-label": "이슈 라벨 알약 하나(Issue label). 배경색으로 분류를 나타낸다",
  "keybinding-hint": "단축키를 기호와 글자로 나란히 보이는 칩 줄(shift ⇧ · control ⌃ · k K)",
  label: "테두리만 있는 작은 알약 하나(Default)",
  "label-group": "알약 열여섯 개가 두 줄로 감기며 늘어선 묶음",
  "link-button": "버튼처럼 보이지만 링크로 도는 것(Default). 모양은 기본 버튼과 같다",
  link: "본문 안의 링크 한 줄(Links are great). 색으로만 구분하고 밑줄이 없다",
  "nav-list": "세로 이동 목록 세 줄(Item 1~3). 현재 항목이 배경으로 강조된다",
  "page-header": "화면 제목 한 줄(Title)과 그 아래 경계선. 높이 65px다",
  "page-layout": "머리·본문·옆 칸·바닥 넷으로 나뉜 문서 흐름 레이아웃. 칸마다 이름이 적혀 있다",
  pagination: "이전·다음과 쪽 번호가 한 줄에 놓인 쪽 넘김 줄",
  popover: "제목·본문·버튼을 담아 떠 있는 작은 판. 기준 원소를 가리키는 꼭지가 달린다",
  "progress-bar": "가로로 길고 8px 높이인 진행 막대의 빈 트랙. 채워진 부분이 없는 상태다",
  radio: "동그란 라디오 단추와 라벨 한 쌍(Label)",
  "radio-group": "제목(Choices) 아래 라디오 셋이 세로로 선다. 하나만 고를 수 있다",
  "relative-time": "시각을 사람이 읽는 꼴로 적은 글 한 줄(on Jan 1, 2020)",
  "scrollable-region": "넘치면 스스로 스크롤 영역이 되는 칸. 안에 줄바꿈 없는 긴 글이 들어 있다",
  "segmented-control": "붙어 있는 칸 셋 중 하나만 눌린 토글 줄(Preview · Raw · Blame)",
  select: "라벨과 드롭다운 한 쌍. 접힌 상태에서 고른 값이 보인다",
  "select-panel": "라벨(Labels)과 고른 값들(bug, good first issue)을 보이는 고르기 칸. 목록은 닫혀 있다",
  spinner: "도는 원형 대기 표시와 그 아래 글(Loading)",
  "split-page-layout": "머리·옆 칸·본문·바닥으로 나뉘고 옆 칸과 본문 사이를 끌어 넓히는 레이아웃. 뷰포트에 꽉 찬다",
  stack: "자식 셋(First·Second·Third)을 일정한 틈으로 세로로 쌓는 배치 상자",
  "state-label": "상태를 아이콘과 글로 알리는 알약 하나(Open)",
  "sub-nav": "이동 링크 셋이 붙어 한 덩어리가 된 줄(Home · Documentation · Support)",
  tabs: "탭 셋과 그 아래 내용 칸. 고른 탭에 밑줄 대신 배경이 붙는다",
  text: "글 한 줄(Default Text). 크기·굵기·색을 props로 정한다",
  "text-input": "라벨과 한 줄 입력칸 한 쌍(Default label)",
  textarea: "라벨과 여러 줄 입력칸 한 쌍. 높이가 넉넉하고 오른쪽 아래에 크기 손잡이가 있다",
  timeline: "세로선을 따라 아이콘과 글이 이어지는 이력 목록. 같은 글 셋이 세 마디로 놓인다",
  "toggle-switch": "라벨과 켜짐/꺼짐 스위치 한 쌍. 현재 상태를 글(Off)로도 적는다",
  token: "지울 수 있는 작은 알약 하나(token)",
  "tooltip-v2": "기준 원소 위에 떠서 설명을 주는 작은 검은 판(Delete)",
  "topic-tag": "주제를 나타내는 둥근 알약 하나(react). 링크로 돈다",
  "tree-view":
    "접히는 트리 — 폴더(src) 아래 파일 셋이 들여쓰기로 붙고, 각 줄 오른쪽에 상태 글(Added·Modified)이 적힌다",
  truncate: "폭을 넘으면 말줄임으로 자르는 글 한 줄(Some example text)",
  "underline-nav": "밑줄로 현재 자리를 보이는 이동 줄(Code · Pull requests · Actions · Projects · Wiki)",
  "underline-panels": "밑줄 탭 셋과 그 아래 내용 칸(Panel 1)이 한 덩어리로 묶인다",
};
